### ISSUE TITLE
Design poster template

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/convenings#2]
Based on discussion from MozillaFoundation/plan#683 we'll design a poster template to be used at various MoFo and community-run events.

cc @cassiemc

**Comment by edrushka** [comment]
For this first template, we'll do a poster with WiFi network name and password (hackable, since this always changes at the last minute).

**Comment by cassiemc** [comment]
Wondering about the reusability of certain assets. Ie. would they be carted/shipped from event to event, or always printed/made onsite?

**Comment by edrushka** [comment]
Some printed material could potentially be reused:
- Photo consent signage
- 'Drop Your Lanyards Here' poster
- 'Register Here' poster
- Participation guidelines poster
- 'What is Mozilla?' context poster

@Saallen is re-using posters realistic, or is it too much effort to ship them from venue to venue without damaging them?

**Comment by Saallen** [comment]
@edrushka It would be a waste of time and effort to post them around the place. Unless you are getting foamex boards printed then the posters will be ripped or crumbled. I do not recommend foamex boards as they are expensive.

**Comment by edrushka** [comment]
There are 2 types of info posters:

### Headline posters (only say one thing)
- Drop Your Lanyards Here
- Register Here
- Signage designating each space (Hive Chicago Buzz example [here - page 6](https://docs.google.com/document/d/1pefmuP6bp2lElMNCna8QB4JwmDlgwaIfAkmn21E0bDw/edit))

### Informational posters (communicates more detailed content)
- Photo consent (MozFest example [here](https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_eeEVHZmZ4ZjJtYWc&usp=sharing#), Hive Chicago Buzz example [here - page 5](https://docs.google.com/document/d/1pefmuP6bp2lElMNCna8QB4JwmDlgwaIfAkmn21E0bDw/edit) )
- Participation guidelines (I can create a shorter version of [this](https://github.com/mozilla/participation-org/blob/master/global_events/leadership_summit/code-of-conduct.md))
- What is Mozilla? (This needs to be written. Filed ticket #5)
- Wifi network and password info - must be hackable (Hive Chicago Buzz example [here - page 6](https://docs.google.com/document/d/1pefmuP6bp2lElMNCna8QB4JwmDlgwaIfAkmn21E0bDw/edit))

**Comment by edrushka** [comment]
Final copy for Participation Guidelines poster (from #6). Please note that this is the poster text only. Event hosts still need to let attendees know the consequences of unacceptable behaviour and how to file reports.

**How to participate at this event:**

To support a happy, productive, and safe event experience that can welcome new ideas and inspiration for all attendees, we request that you:
- be respectful and welcoming
- try to understand different perspectives
- do not threaten violence or harassment
- do not make demeaning jokes or comments
- empower others
- strive for excellence

Read Mozilla's full Participation Guidelines here: https://www.mozilla.org/en-US/about/governance/policies/participation/

**Comment by edrushka** [comment]
I stumbled across Google's WomenTechmakers poster on twitter: https://twitter.com/kirstie_j/status/710192738923384833

**Comment by edrushka** [comment]
@Melechuga what day do you need this poster by in order to get it printed for your event? Thanks!

**Comment by Melechuga** [comment]
Hey @edrushka The event is on Tuesday, March 29th.
Would be great to have the poster by mid-next week to make sure we get it printed in time. I suppose Monday, March 28th at the latest if I can print it in the office.

Thanks!

**Comment by edrushka** [comment]
I don't think the SF office printers can do this size, so we'll def. try to get it to you by mid week to give you enough time.

**Comment by edrushka** [comment]
Here's the poster mockup on redpen: https://redpen.io/bk42aec368f401995a

My inclination is to choose the top right design and to swap out the long URL with a shortlink. If others feel differently, kindly weigh in soon as I want to ensure @Melechuga  has adequate time to print this before her event. Thanks.

**Comment by sabrinang** [comment]
Participation poster exported here in 3 sizes (8.5"x11", 11"x17", 18"x24"): https://drive.google.com/open?id=0B4Q8pzCpDS_eVHJ0Mlc2MWUtX0U

**Comment by sabrinang** [comment]
@Melechuga ^ Let me know if you need me to make any adjustments to these posters?

**Comment by sabrinang** [comment]
I got feedback great from @Melechuga and will recap here!

The blue colour on dark background become hard to read especially if printers do not print as saturated as commercial printers. For example, blue URL doesn't stand up against the gray-ish backgrounds. I have changed this to the lightest blue in our unified palette. Looking at it now it probably can be a more subtle tint of that colour perhaps.
![poster-print_example](https://cloud.githubusercontent.com/assets/2492510/14124959/804aaf40-f5bd-11e5-8d37-34cbbaddd76f.png)

Also, similar feedback to the name label applies here to supply organizers with some print tips as we figured that printing settings differ.

**Comment by sabrinang** [comment]
Some design feedback I got from this weeks crit:
- try an alternative layout with mozilla wordmark being more subtle after title heading or at the bottom
- consider arrangement of dos and do nots (clustered together or sandwiched apart)
- try alternative to dino red colour (may feel associated with warning signs, negative feelings) but I also do think it has strong association for the Mozilla brand
- design with an intentional border so margins for office printers/no trim appear integrated in the design
- test colours for print

**Comment by arlissc** [comment]
@sabrinang - we (Mozilla Science Lab) would also like to offer this poster to our global sprint site hosts and are wondering if you have a current template that we can use. thx

**Comment by edrushka** [comment]
Sabrina and I discussed the design crit and user testing feedback. Decision is the use the lighter blue (for better office printing) and add an intentional border.

We'll export that version, and consider this asset complete until we get a few more months of user testing.

**Comment by edrushka** [comment]
@arlissc you can find the templates here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_eVHJ0Mlc2MWUtX0U&usp=drive_web 

Sabrina will have the final, light-blue version exported into that folder by the end of today.

**Comment by sabrinang** [comment]
Poster format will be used in a "What is Mozilla" poster too https://redpen.io/rd1e14a0fe8752e2cf

**Comment by sabrinang** [comment]
What is Mozilla, Participation Guideline posters and .ai file can be found exported here: https://drive.google.com/folderview?id=0B4Q8pzCpDS_eR1U3a0hIdzJtZjQ&usp=sharing

@auremoser you can download the .ai file contains posters in 8.5x11, 11x17, 18x24 where you can change the text of the example poster using [fira sans](http://www.carrois.com/en/fira-4-1/) and the other two posters are there for reference too

<img width="1009" alt="screen shot 2016-04-25 at 10 46 52 am" src="https://cloud.githubusercontent.com/assets/2492510/14793466/3271ff4a-0ad4-11e6-8135-bfea686110b9.png">

**Comment by edrushka** [comment]
cc @vazquez

**Comment by auremoser** [comment]
Thank you so much all! We [Science Lab] are putting together swag materials for the global sprint and our host sites, and these resources are great, thanks @sabrinang and @edrushka especially.
