### ISSUE TITLE
Write "What is Mozilla?" copy for display at convenings

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/convenings#5]
One of the convenings design assets we realize we need is text that explains, in very high-level terms, what the Mozilla project is. At some events, participants don't understand what Mozilla is or how and why it's involved in the event. Some people mistakenly think Mozilla is simply a corporate sponsor. We'd like to create a standard piece of copy that can be printed in poster form, or perhaps as part of the event handout, that explains the Mozilla mission.

@KevZawacki does this text already exist somewhere? I really like the opening 4 paragraphs of the [2014 State of Mozilla report](https://www.mozilla.org/en-US/foundation/annualreport/2014/). Is there somewhere else I should be looking?

**Comment by KevZawacki** [comment]
@edrushka A few other places to draw from:

[mozilla.org/foundation](https://www.mozilla.org/en-US/foundation/):

"The nonprofit Mozilla Foundation is the organizational home of the Mozilla Project, a global community and public interest initiative that believes the Web should be open and accessible to all. To protect the Web as a public resource and empower its users, we create open source products, teach 21st-century skills and spur grassroots advocacy campaigns. All this is made possible by full-time staff and thousands of volunteers around the world."

Or the [2020 strategy one-pager](https://docs.google.com/document/d/1vSnwN1giStIUODt1FH5XhhuQK9fot88kgjqu1q0Oi-Y/edit) Sam Burton and I are working on (still a draft):

"Mozilla is a global community devoted to a singular mission: protecting the open Internet. We believe the Internet must remain a global public resource, open and accessible to all.   The success of this mission relies on Mozilla’s community members — both staff and thousands of volunteers — who are the brightest makers, coders, designers, teachers and activists around."

**Comment by edrushka** [comment]
Thanks Kevin!

**Comment by edrushka** [comment]
cc @Melechuga @Saallen

**Comment by edrushka** [comment]
What do you all think of this:

**What is Mozilla?**
Mozilla is a global community devoted to a singular mission: protecting the open Internet. We believe the Internet must remain a global public resource, open and accessible to all. 

Together, Mozilla staff and thousands of volunteers build products (we're best known for the Firefox web browser), organize communities, spread digital literacy and citizenship skills, and mobilize people around the world to stand up for the web and its users. 

Mozilla's heart is the community: thousands of makers, coders, designers, teachers and activists. Join us! 

www.mozilla.org
[could have a hackable space here for event/program-specific join asks]

**Comment by ldecoursy** [comment]
Suggestion: 

**What is Mozilla?**
Mozilla's mission is to protect the Internet as a global public resource, open and accessible to all.

Together, Mozilla staff and thousands of volunteers build products (we're best known for the Firefox web browser), organize communities, teach digital literacy skills, and mobilize citizens around the world to stand up for the web and its users.

Mozilla's heart is its community of makers, coders, designers, educators and activists. Join us!

**Comment by edrushka** [comment]
@ldecoursy  is that suggestion because it felt repetitive or because you don't want to reduce the project to a single mission?

**Comment by ldecoursy** [comment]
Both. Original has several references to "community", also want to respect that community members may align with our mission, but be devoted to their own mission, if that makes sense.

**Comment by edrushka** [comment]
@KevZawacki are you cool with this?

**What is Mozilla?**
Mozilla is a global community working to protect the Internet as a public resource, open and accessible to all.

Together, Mozilla staff and thousands of volunteers build products (we're best known for the Firefox web browser), organize communities, teach digital literacy skills, and mobilize citizens around the world to stand up for the web and its users.

Mozilla's heart is its community of makers, coders, designers, educators and activists. Join us! 

www.mozilla.org
[hackable space here for event/program-specific join asks]

**Comment by edrushka** [comment]
^ also @KevZawacki can you let me know the latest Moz copy rules on capitalizing web and internet. Thanks.

**Comment by KevZawacki** [comment]
@edrushka Excellent! :+1: 

Last I heard, we are still capitalizing both "Web" and "Internet." I will send you a calendar invite for the daily capitalization standup.

**Comment by Saallen** [comment]
Yo, loving lainies copy but throwing a spanner in the works -  I think we need to reference Open- it is a major topic of conversation and the second more frequent word associated with Mozilla outside of firefox. We also need to then include what we mean by open for new people hearing this for the first time.

**Comment by edrushka** [comment]
Yes! Good point. I'll do a revision that includes Open.

**Comment by edrushka** [comment]
How's this:

Working open is one of our core values. This means working in public spaces like Github, shared Google docs, community calls and etherpads to encourage a culture that is both public and participatory. We strive to create ways for 'outsiders' to become 'insiders'.

**Comment by edrushka** [comment]
@sabrinang Let's design the poster with the following text:

What is Mozilla?
Mozilla is a global community working to protect the Internet as a public resource, open and accessible to all.

Together, Mozilla staff and thousands of volunteers build products (we're best known for the Firefox Web browser), organize communities, teach digital literacy skills, and mobilize citizens around the world to stand up for the Web and its users.

Working open is one of our core values. This means working in public spaces like Github, shared Google docs, community calls and etherpads to encourage a culture that is both public and participatory. We strive to create ways for 'outsiders' to become 'insiders'.

Mozilla's heart is its community of makers, coders, designers, educators and activists. Join us!

www.mozilla.org
[hackable space here for event/program-specific join asks]

**Comment by edrushka** [comment]
@sabrinang has posted a design: https://redpen.io/rd1e14a0fe8752e2cf  It matches the styling of the [Participation Guidelines Poster](https://redpen.io/xhd7a194077dc25cea).
