### ISSUE TITLE
Write a shorter version of Participation Guidelines for templates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/convenings#6]
Need a shorter version of this: https://github.com/mozilla/participation-org/blob/master/global_events/leadership_summit/code-of-conduct.md
Science Lab also has a good version: https://docs.google.com/document/d/1QIqgTLajUYLZi9jiYeNxzttIlUvuo1VqPQ5htPWrf2k/edit

cc @sabrinang - I'll work on this here.

**Comment by davidascher** [comment]
Why is shorter better?

Codes of conduct are a well explored area, and I think it would be bad to
lose some of the community learnings there without a clear shared
understanding of the reason why we want shorter.  They have also been
discussed in a public process, and that engagement needs to be respected.

(btw, I'm not saying longer is better, just want to understand the why
behind this issue)

I'm no expert, but see
http://www.ashedryden.com/blog/codes-of-conduct-101-faq if curious on the
topic.

**Comment by edrushka** [comment]
Because this will be printed on a poster, and possibly even on a passport-sized handout. This ticket is for the assets template only, and is not MoFo's "official, comprehensive policy".

**Comment by edrushka** [comment]
I've taken a crack at shortening the guidelines for a poster. It's still very long, but I thought I'd ask for feedback before cutting any further. This is mostly exact language from The Participation Team's [Mozillian Community Event Safety Guidelines](https://github.com/mozilla/participation-org/blob/master/global_events/leadership_summit/code-of-conduct.md), which has been thoroughly developed with the community, plus a 'working open' point inspired by the [MozFest guidelines](https://2015.mozillafestival.org/guidelines). I also consulted the link from @davidascher above to ensure we are adhering to best practices.

@Saallen @arlissc @erikao @omnignorant @LindseyFrost - what are your thoughts about displaying this in poster form at events? 
https://docs.google.com/document/d/1SCGypX_ajQM5pDdF1rPC0E63laCkxsO7yaTmK5ZuDPk/edit#

**Comment by LindseyFrost** [comment]
@edrushka I love the idea of displaying something like this at events, even if it's just the opening paragraph with the longer text available in a "passport" style as you mention.  The only thing I'll note is that it might be hard for one text to work across all geographies.  For example the "(or lack thereof)" in the opening paragraph could cause so much drama in my deep south US context that every event might become about that phrase.  Not that it shouldn't be there (!) but wanted to flag.

**Comment by davidascher** [comment]
I'd love to find out more about the specific drama you're worried about
Lindsey, but I suspect that's best done 1-1; I'll make a general point:

Personally, I'm willing for us to "lose" people for whom any of these
clauses are controversial, and I think making the language geographically
specific is unviable.  Inclusivity is a non-negotiable core cultural trait
we are working hard to strengthen, both as an organization and as a
movement.  We stand a lot more to win by taking a clear, unambiguous stand
and being particularly welcoming to those folks who see these cultural
norms as a marker of a desirable convening.

I'm also fine with other organizations having events with different
boundary conditions, and us finding alliances and making it possible for
those differences to co-exist.  But I believe a Mozilla event should have a
consistent core.  (I expect that jointly organized events probably need
explicit negotiations).

**Comment by LindseyFrost** [comment]
I certainly agree, David! We should be aware, though, that some of these clauses will be controversial, particularly in areas (like mine) where perhaps the dialogue isn't so common and the conversation not so normalized. If we're going to post this language at events (and we should), we also need to give those staff members leading these events strong professional development and support to understand how to handle the conversations such a poster might bring up. I don't mind "losing" the intolerant, but I do mind losing people for whom these sorts of statements might be new and surprising simply because I didn't know how to direct the conversation in the right way or what appropriate feedback to provide.

**Comment by davidascher** [comment]
Totally agreed! We might want to do some research for some of that
professional training and identify both curriculum and maybe
workshop/discussion options.

**Comment by edrushka** [comment]
An important part of a robust code of conduct is providing education, training and resources for event hosts and volunteers on a) why we even _have_ a code of conduct, and b) how to respond to questions and incident reports. 

We've currently called out this staff education piece in our Convenings Team 2016 Plan, but this conversation makes it clear that the training needs to take into account specific cultural/geographical considerations. @LindseyFrost, thanks for highlighting this.

**Comment by edrushka** [comment]
If having the full guidelines printed out seems heavy-handed, we could also do a "quick and friendly" version.

**Here's the MozFest short version:**
How to treat each other
be respectful and welcoming
try to understand different perspectives
do not threaten violence
empower others
strive for excellence
don‘t expect to agree with every decision

**And here's what the Science Lab used for their WOW:**
The Mozilla Science Lab is dedicated to providing a harassment-free learning experience for everyone, regardless of gender, sexual orientation, disability, physical appearance, body size, race, religion, or choice of text editor. We do not tolerate harassment of participants in any form.
All communication should be appropriate for a professional audience including people of many different backgrounds. Sexual language and imagery is not appropriate for any event.
Be kind to others. Do not insult or put down other attendees.
Behave professionally. Remember that harassment and sexist, racist, or exclusionary jokes are not appropriate.
Attendees violating these rules may be asked to leave the event at the sole discretion of the conference organizers without a refund of any charge that may have been levied.
Thank you for helping make this a welcoming, friendly event for all.

The MozFest version (with the URL of the full guidelines) could work really well on a poster, IMO.

cc @secretrobotron

**Comment by secretrobotron** [comment]
Just an observation about a "short" version (of anything, including a participation guideline, really): neither of those seems to convey a sense of **why** these rules are important to follow (beyond making people feel bad). But, the full participation one does have a general "goal":

> "... to support a happy, productive, and safe event experience that can **welcome new ideas and inspiration for all attendees**..."

I wonder if it's worth mentioning that these guidelines are worth following so that people can be happy and productive and engaged without worry.

**Comment by edrushka** [comment]
+1 to a sentence or two of context to frame the "short" guidelines.

**Comment by davidascher** [comment]
Also, a pointer to the long form, which has important details, path to
enforceability, etc.

**Comment by Saallen** [comment]
+1 to the friendly short context sentence and +1 to the small new user friendly list.
Being aware of the audience, and the questions these guidelines raise, its important that we set ourselves and the audience up for clarity, understanding and success.

**Comment by cassiemc** [comment]
:heart: this conversation.

**Comment by edrushka** [comment]
What do you all think of this:

**How to participate at this event:**

 To support a happy, productive, and safe event experience that can welcome new ideas and inspiration for all attendees, we request that you:
- be respectful and welcoming
- try to understand different perspectives
- do not threaten violence or harassment
- do not make sexist or racist jokes 
- empower others
- strive for excellence

Read our full Code of Conduct here: [url]

**Comment by ldecoursy** [comment]
4th bullet shouldn't just be about jokes - maybe "do not make offensive comments or jokes?"

I might add "avoid using jargon or slang"

Should we start with "do's" then list "don'ts"

**Comment by xmatthewx** [comment]
An Open Web fellow is developing an "online tool for building a thorough and well-supported Code of Conduct specific to a community's online and/or offline environment." Would be good to share insight: https://github.com/gembarrett/coconduct-builder.  (Added to the [Network Pulse prototype](https://xmatthewx.github.io/network-pulse/) )

**Comment by edrushka** [comment]
cc @Melechuga

**Comment by edrushka** [comment]
@xmatthewx thanks for posting that! Melissa (who's going to be our test use-case for this poster later this month), Sarah and I just had a good chat about how additional codes of conduct could be introduced. 

@ldecoursy thanks for your feedback! Comments below.

> 4th bullet shouldn't just be about jokes - maybe "do not make offensive comments or jokes?"

I can change to "do not make demeaning jokes or comments" which is closer to the original

> I might add "avoid using jargon or slang"

This isn't part of Mozilla's [official code of conduct](https://github.com/mozilla/participation-org/blob/master/global_events/leadership_summit/code-of-conduct.md), and people might not know what constitutes jargon or slang in the event context, so I'd argue against adding this.

> Should we start with "do's" then list "don'ts"

I'd prefer to end on a high/positive note (a "do").

**Comment by edrushka** [comment]
Thanks for weighing in on this everyone. Closing now. Will re-open if feedback from event participants indicates this needs work.
